### ISSUE TITLE
how to set the reapacket's  number

### ISSUE THREAD

**Issue by xzpfengxi** [joselyncui/RedPackets#1]
I haven't added this function yeat, and I plan to add this feature, and the countdowning function in the future

**Comment by joselyncui** [comment]
I haven't added this function yeat, and I plan to add this feature, and the countdowning function in the future

**Comment by joselyncui** [comment]
Hi, I already finish those functions, please checkout branch **accelerate** and look at the **MeteorShowerActivity**
